# This is a basic workflow to help you get started with Actions

name: Remote Resume Google Drive Upadate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["remote-job-resume"]
  pull_request:
    branches: ["remote-job-resume"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Clone the Project.
        uses: actions/checkout@v3

      - name: Checkout branch remote-job-resume.
        run: git checkout remote-job-resume

      - name: Rename filename
        run: |
          mv Yash_Verma_CV.tex Yash_Verma_CV_Remote.tex
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Yash_Verma_CV_Remote.tex
          compiler: pdflatex
      

      - name: Upload Resume to google drive.
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: "Yash_Verma_CV_Remote.pdf"
          overwrite: true
          folderId: ${{ secrets.ID }}
          useCompleteSourceFilenameAsName: true
